//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryReader.Debian.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RepositoryReader.Debian.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Package: azdata-cli
        ///Version: 20.2.5-1~buster
        ///Architecture: all
        ///Section: python
        ///Priority: extra
        ///Installed-Size: -1
        ///Maintainer: AZDATA CLI Team &lt;dpgswdist@microsoft.com&gt;
        ///Description: AZDATA CLI
        /// AZDATA CLI, a multi-platform command line experience for SQL.
        ///Homepage: http://www.microsoft.com/sql
        ///Depends: unixodbc, libkrb5-dev, libc6 (&gt;= 2.28), libssl1.1 (&gt;= 1.1.0)
        ///SHA256: cdefde5e1394dd798a8f47b1e5ee30a25f2d2e70a8ac2ae78fd05a0ac858911d
        ///Size: 83195028
        ///Filename: pool/main/a/azdata-cli/azdata-cli_20.2.5-1~buster_ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string BrokenParameters {
            get {
                return ResourceManager.GetString("BrokenParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string EmptyParameters {
            get {
                return ResourceManager.GetString("EmptyParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Package: azdata-cli
        ///Version: 20.2.5-1~buster
        ///Architecture: all
        ///Section: python
        ///Priority: extra
        ///Installed-Size: 475861
        ///Maintainer: AZDATA CLI Team &lt;dpgswdist@microsoft.com&gt;
        ///Description: AZDATA CLI
        /// AZDATA CLI, a multi-platform command line experience for SQL.
        ///Homepage: http://www.microsoft.com/sql
        ///Depends: unixodbc, libkrb5-dev, libc6 (&gt;= 2.28), libssl1.1 (&gt;= 1.1.0)
        ///SHA256: cdefde5e1394dd798a8f47b1e5ee30a25f2d2e70a8ac2ae78fd05a0ac858911d
        ///Size: 83195028
        ///Filename: pool/main/a/azdata-cli/azdata-cli_20.2.5-1~bus [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string NormalParameters {
            get {
                return ResourceManager.GetString("NormalParameters", resourceCulture);
            }
        }
    }
}
